### ISSUE TITLE
Inheritance principle not taken into consideration by validator

### ISSUE THREAD

**Issue by sappelhoff** [bids-standard/legacy-validator#477]
When validating datasets for BEP006_EEG, I found that the validator ignores the **Inheritance Principle**, see section 3.5 in the [specification](http://bids.neuroimaging.io/bids_spec1.1.0.pdf).

Example: The [eeg_matchingpennies](https://github.com/INCF/BIDS-examples/tree/bep006_eeg/eeg_matchingpennies) dataset should need only one single `task-matchingpennies_eeg.json
` defined at the root level. This file would then be inherited by all other nodes that should have an `eeg.json` ... however, the validator was only satisfied after such a file had been added for every subject in their respective sub-XX directories.

See the [original issue](https://github.com/robertoostenveld/bids-validator/issues/1#issuecomment-393144522)

 @robertoostenveld found a similar problem when trying to define a `channels.tsv` file. This problem does not seem to be EEG specific.

**Comment by chrisgorgo** [comment]
Indeed inheritance principle is not fully implemented. Right now it works only for metadata (json and events) describing .nii fieles (see https://github.com/INCF/bids-validator/blob/master/validators/nii.js#L34).

**Comment by sappelhoff** [comment]
The issue also applies the other way around: I am now working on a dataset where I have specified a `task-<>_events.json` file at the root directory ... however for a few individuals I also have to specify `sub-<>_task-<>_events.json` files to adjust the information on how to interpret the `sub-<>_task-<>_events.tsv` for their specific cases.

Although this should be fine through the inheritance principle, I get:


```	
1: Files with such naming scheme are not part of BIDS specification.
This error is most commonly caused by typos in file names that make them not BIDS compatible.
Please consult the specification and make sure your files are named correctly.
If this is not a file naming issue (for example when including files not yet covered by the BIDS specification)
you should include a ".bidsignore" file in your dataset.
Please note that derived (processed) data should be placed in /derivatives folder and source data
(such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder.
(code: 1 - NOT_INCLUDED)

		./sub-002/eeg/sub-002_task-replay_events.json
			Evidence: sub-002_task-replay_events.json
```

**Comment by sappelhoff** [comment]
Could we tag this "high priority" or at least "enhancement" (both?)? I feel like this is not getting the attention it deserves, especially because the inheritance principle is so prominent in the main specification. @chrisfilo @nellh

**Comment by chrisgorgo** [comment]
This is relevant to this issue https://github.com/INCF/bids-validator/pull/514

**Comment by chrisgorgo** [comment]
This should be resolved in the current version @sappelhoff could you test?

**Comment by sappelhoff** [comment]
Using my test case (see below), the inheritance principle is not yet fixed/implemented fully:

1. `git clone https://github.com/incf/BIDS-examples`
2. `cd BIDS-examples; git checkout bep006_eeg; cd eeg_matchingpennies`
3. (a)  `bids-validator --bep006 .`

this exits cleanly.

however, if we change the steps to do instead:

3. (b) `find . -type f -name 'sub-*_task-*_eeg.json' -delete`
4. `bids-validator --bep006 .`

.. then I get:

> [ERR]  The directory . failed an initial Quick Test. This means the basic names and structure of the files and directories do not comply with BIDS specification. For more info go to http://bids.neuroimaging.io/

The test case `eeg_matchingpennies` is a pretty straight forward case, where we have the same modality specific sidecar for each subject, i.e. `task-matchingpennies_eeg.json` is equal for all subjects. This is why there is a "global" `/task-matchingpennies_eeg.json` file at the root level to be inherited by each subject. However the test shows that the bids-validator only exits cleanly if each subject has their own `sub-XX_task-matchingpennies.json` file (see step 3a). Upon removing these (see step 3b), the validator crashes.

**Comment by chrisgorgo** [comment]
Because you are getting a "failed initial Quick Test" error I suspect this is a different problem potentially unrelated to the inheritance principle. @olgn could you have a look?

**Comment by sappelhoff** [comment]
Hi again, I am still troubled by this issue while preparing datasets for the EEG extension.

I am pretty sure that this has something to do with the inheritance, the two test cases I report show that having a single modality specific file (eeg.json in this case) at the *subject level* suffices to not run into a failed QuickTest ... however, the more natural case of having an eeg.json at the root and having all subjects inherit that one ... always fails.

The situation is different for iEEG (see test case 3), but also a bit weird. I have prepared three test cases to follow along:

**Using bids-validator version 1.1.1**

# test case 1 (see also previous comments)
```bash
# Clone our test case (move to rishikesh example)
git clone https://github.com/bids-standard/bids-examples
cd bids-examples
git checkout bep006_eeg
cd eeg_matchingpennies

# Make an initial test without any changes,
# validator is fine ... there are eeg.json files defined
# at the root AND for each subject ... they are all equivalent
# so the eeg.json at the root alone should suffice
# anyhow, for now, this exits cleanly
bids-validator --bep006 .

# To test whether the behavior is as expected,
# we remove the subject wise eeg.json files
# the one at the root should be inherited and suffice
find . -type f -name 'sub-*_task-*_eeg.json' -delete

# Check it ... it fails: QuickTest
bids-validator --bep006 .

# Can we repair it by adding a single eeg.json that is subject
# specific? Checkout one of the deleted files to "restore" it
git checkout sub-05/eeg/sub-05_task-matchingpennies_eeg.json

# Check it: exits cleanly (no failed QuickTest)
bids-validator --bep006 .

# Reset everything and try again if you like
git reset --hard

```

# test case 2 (showing that it is not dataset specific)
```bash
# Given that you ran test case 1 first
# move to root of bids-examples ... and from there to another dataset
cd ..
cd eeg_rishikesh

# Make an initial test without any changes,
# validator is fine (no failed Quick Test) ... using "find", we see that
# there is only a single eeg.json defined
# at a subject level, somehow detected and applied to complete dataset
bids-validator --bep006 .

# Copy the single eeg.json file, and move it to the root, making it subject
# independent 
cp ./sub-Expert01/ses-01/eeg/sub-Expert01_ses-01_task-medprobe_eeg.json .
mv sub-Expert01_ses-01_task-medprobe_eeg.json task-medprobe_eeg.json

# validator is fine with that
bids-validator --bep006 .

# now remove the single subject specific eeg.json, we remain only
# with the subject independent one that we just copied to the root
rm ./sub-Expert01/ses-01/eeg/sub-Expert01_ses-01_task-medprobe_eeg.json

# The validator throws an issue (initial Quick Test failed)
bids-validator --bep006 .

# Reset everything and try again if you like
rm ./task-medprobe_eeg.json
git reset --hard
```

# test case 3 (the situation is different for iEEG)

```bash
# first, move to root of bids-examples
# checkout the iEEG branch
git checkout bep010_ieeg
cd ieeg_filtered_speech

# run a test, no failed QuickTest
# not the change of flag bep010
# Each subject has their own ieeg.json file
# although they are all the same
bids-validator --bep010 .

# remove all subj wise ieeg.jsons
find . -name '*ieeg.json' -delete

# strangely, the validator does not give a failed
# Quick Test here ... only the "Available Tasks" output
# is empty ... there SHOULD be an error though
bids-validator --bep010 .

# What happens if we have a single ieeg.json at the root
# that is participant independent?
git checkout sub-cm4/ieeg/sub-cm4_task-FilteredSpeech_ieeg.json
cp sub-cm4/ieeg/sub-cm4_task-FilteredSpeech_ieeg.json .
mv sub-cm4/ieeg/sub-cm4_task-FilteredSpeech_ieeg.json task-FilteredSpeech_ieeg.json
rm sub-cm4_task-FilteredSpeech_ieeg.json

# Available Task is back and there is no failed QuickTest
# inheritance seems to work ...
bids-validator --bep010 .

# Reset everything and try again if you like
git reset --hard

```

It would be great to get some help with making these test cases work as expected. @chrisfilo @olgn

**Comment by chrisgorgo** [comment]
My best bet is that a /eeg.json file is not recognized as bids compatible
and the regular expressions need to be adjusted.
