### ISSUE TITLE
bids-validator v1.4.2 - Units error in channels.tsv file

### ISSUE THREAD

**Issue by greydongilmore** [bids-standard/legacy-validator#917]
Running the validator on an iEEG dataset and getting an error within the ***_channels.tsv** file. The error is associated with the unit abbreviation (μV): `Subunit (Î¼V) of unit Î¼V is invalid.`. Anyone else running into this issue?

**Comment by effigies** [comment]
Seems related to #878 with TSV files being loaded as latin1 instead of utf8.

cc @david-nishi

**Comment by greydongilmore** [comment]
Yes, I agreed. Same error.

**Comment by david-nishi** [comment]
This could be a case of double-encoded utf-8.
```
// javascript

decodeURIComponent(escape('Î¼V'))
// returns 'µV'
```
It's tricky to detect, but passing a decoded form of strings that have failed the unit validation process back through for a second check would allow us to bypass that, I think with minimal side-effects. Ticket is in dev backlog.

**Comment by sappelhoff** [comment]
@greydongilmore has this been fixed with #948 ? If not, please reopen.

**Comment by greydongilmore** [comment]
When using `μV` in my bids code I still get a `INVALID_TSV_UNITS` error. 
`Subunit (Î¼V) of unit Î¼V is invalid.`

**Comment by sappelhoff** [comment]
mmh could it be that you are using the GREEK MU sign: https://www.compart.com/de/unicode/U+03BC

instead of the MICRO SIGN: https://www.compart.com/de/unicode/U+00B5

and the MICRO SIGN (µ) is the one we expect in the validator: 

https://github.com/bids-standard/bids-validator/blob/3d5fb2f2d95e098b62a2ca663a203b4baada65c5/bids-validator/utils/unit.js#L92

note that we are aware that this is troublesome and weird, because the characters *look* exactly the same. We are trying to fix this problem. Current discussion in: https://github.com/bids-standard/bids-specification/pull/411

Please let me know if changing to MICRO SIGN is fixing your issue :-)

**Comment by greydongilmore** [comment]
Updating my bids code using `\u00B5` I am getting the same error with the updated decoding: `Subunit (ÂµV) of unit ÂµV is invalid`

**Comment by sappelhoff** [comment]
Closing, because we are not validating units anymore. We can come back to this once we re-implement unit validation (if we do)
